### ISSUE TITLE
feat: support `!` postfix for breaking changes

### ISSUE THREAD

**Issue by nberlette** [denoland/bump-workspaces#33]
As is common with conventional commits, breaking changes are often denoted with a `!` rather than the `BREAKING` commit type. Supporting this syntax will allow more flexibility for users of the package. It will also allow breaking changes to occur in multiple different types of commits, which is a more realistic scenario in the real world.

I prefaced the title with `feat:` because I just begun implementing this. I'll open a PR for it later today or tomorrow.

Thanks!

**Comment by kt3k** [comment]
implemented by #35

**Comment by kt3k** [comment]
Published as 0.1.22. Thanks for your suggestion! https://jsr.io/@deno/bump-workspaces@0.1.22
